### ISSUE TITLE
image Crop bug

### ISSUE THREAD

**Issue by ja8zyjits** [inveniosoftware/flask-iiif#23]
In Image Cropping I found a small bug or issue or may be I did it wrong.
The second image height after cropping is more than the first image, though both were given identical coordinates.
Steps to reproduce:

```python
from PIL import Image
original = Image.open("/tmp/photolog/post_4.png")
original.crop((0,114,1366,449)).show()
```
![correct1](https://cloud.githubusercontent.com/assets/10775161/12422916/30a25ede-beef-11e5-986e-79e60b1b4481.png)

```python
from flask_iiif.api import IIIFImageAPIWrapper
image = IIIFImageAPIWrapper.from_file("/tmp/photolog/post_4.png")
image.crop('0,114,1366,449')
image.image.show()
```
![wrong1](https://cloud.githubusercontent.com/assets/10775161/12422913/2a4853cc-beef-11e5-9854-69e0b136c5ae.png)

Well you can see that it doesnt make much of difference generally, but it is something that i would like to rectify for myself atleast.
Please let me know if I am doing something wrong.

> python2.7.3
> Pillow==3.1.0
> Flask-IIIF==0.2.0

**Comment by lnielsen** [comment]
What is the difference between the two?

**Comment by ja8zyjits** [comment]
Image height.. The height of the image in the second case is more, though the coordinates are identical... I will update the question... My bad

**Comment by lnielsen** [comment]
Ok got it. The second image is wrong, right? Both says 115x114.

**Comment by lnielsen** [comment]
Ah, sorry, got it now. The two images is the result of the crop. Sorry, being a bit slow here :-)

**Comment by ja8zyjits** [comment]
Exactly...thank you.

**Comment by lnielsen** [comment]
This is due to difference in APIs:

PIL takes:
x1,y1,x2,y2
https://pillow.readthedocs.org/en/3.1.x/reference/Image.html#PIL.Image.Image.crop

IIIF takes:
x, y, **width, height**
http://flask-iiif.readthedocs.org/en/latest/#flask_iiif.api.MultimediaImage.crop

I.e. you should use:
```python
from flask_iiif.api import IIIFImageAPIWrapper
image = IIIFImageAPIWrapper.from_file("/tmp/photolog/post_4.png")
image.crop('0,114,1366,335')
image.image.show()
```

**Comment by ja8zyjits** [comment]
Oh, I knew there will be something wrong in my approach.. Thank you once again.
