### ISSUE TITLE
RFC: Allowing custom filename requests to fallback to "default" quality

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/flask-iiif#29]
A major use case with IIIF for us is to allow the users to download archived images in different resolutions, and in JPG format. We are currently doing this, but the naming convention of IIIF poses a big problem in that all files are then called `default.jpg`.

I propose that we introduce a config variable (e.g. `IIIF_DEFAULT_FALLBACK`) to allow for custom filenames to fallback to the default quality, which is most often in use. 

I have asked this question on the [IIIF discussion group](https://groups.google.com/forum/#!topic/iiif-discuss/VkRG6-26Rzk), who seems to approve. There is also no strict requirement for not doing as I suggest (http://iiif.io/api/image/2.1/#quality).

I have also considered the HTML5 tag `download="filename.jpg"`, but the browser support for this is not very good (neither IE nor Safari supports it). Another suggested method is to utilize the Content-Disposition header, but I can't see how this can be done in a practical manner.

**Comment by egabancho** [comment]
@inveniosoftware/triagers @drjova

**Comment by greut** [comment]
`default.jpg?dl=true`

> For use cases that enable the saving of the image, it is recommended to use the HTTP Content-Disposition header (RFC6266) to provide a convenient filename that distinguishes the image, based on the identifier and parameters provided.
>
> http://iiif.io/api/image/2.0/#a-implementation-notes

**Comment by blixhavn** [comment]
So `default.jpg?dl=custom_filename`

**Comment by greut** [comment]
_custom_filename_ may be extra work to devise. `true` or `1` or `?dl` could be provide a convenient default name `filename-region-size-rotate-quality.format` where the default values could collapse to nothing (if IIIF 2.1 is supported).

**Comment by jirikuncar** [comment]
@greut WDYT about #30?
