### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/flask-iiif#4]
- [ ] compile `RELEASE-NOTES.rst`, `CHANGES`
- [ ] update `flask_iiif/version.py`
- [ ] ...

**Comment by jirikuncar** [comment]
@drjova is there any blocker for release?

--
cc @tiborsimko

**Comment by drjova** [comment]
I don't think but I would like first to see it running with https://github.com/inveniosoftware/invenio/pull/2924 before the release.

**Comment by drjova** [comment]
Tested lgtm! thanks
