### ISSUE TITLE
global: fix build failure

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/flask-iiif#78]
https://travis-ci.org/inveniosoftware/flask-iiif/jobs/656676422
```
$ ./run-tests.sh
lists of files in version control and sdist match
/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sphinx/util/nodes.py:94: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
Warning, treated as error:
autodoc: failed to import module u'cache' from module u'flask_iiif.cache'; the following exception was raised:
cannot import name cached_property
The command "./run-tests.sh" exited with 2.
```
Fix also Travis deprecation:
https://travis-ci.org/inveniosoftware/flask-iiif/jobs/656676422/config

**Comment by dfdan** [comment]
werkzeug 1.0.0 has removed all the caching stuff from contrib to a new library (cachelib). 

In my pending PR I have pegged werkzeug to <1.0.0 to get around this.

**Comment by slint** [comment]
@dfdan We're exploring in the current sprint ways to deploy an Invenio repository-wide way to address this... I'm testing in a local branch ways to make it work for werkzeug > 1.0.0 as well, and will probably open a PR (and possibly update yours as well)
